---
# Default OpenStack environment variables
openstack_project_domain_name: "Default"
openstack_user_domain_name: "Default"
openstack_project_name: "admin"
openstack_tenant_name: "admin"
openstack_username: "admin"
openstack_password: "FKJ5zNaThJDs5IPU34Fp8eKgrGN7YV31nJZZYWZu"
openstack_auth_url: "http://10.100.145.54:5000"
openstack_interface: "internal"
openstack_endpoint_type: "internalURL"
openstack_identity_api_version: "3"
openstack_region_name: "RegionOne"
openstack_auth_plugin: "password"
openstack_project_id: "3154636851a94ce3a608412a215887df"
openstack_domain_id: "default"
openstack_insecure: "true"


docker_image: "mariolan/migratekit:latest"
docker_command: "migrate"
docker_privileged: true
docker_network: "host"
docker_volumes:
  - "/dev:/dev"
  - "/usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro"
docker_env_file: "<(env | grep OS_)"
