---
docker_image: "mariolan/migratekit:latest"
#docker_command: "migrate"
docker_privileged: true
docker_network: "host"
docker_volumes:
  - "/dev:/dev"
  - "/usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro"
docker_env_file: "<(env | grep OS_)"