---
openstack_env:
  OS_PROJECT_DOMAIN_NAME: "Default"
  OS_USER_DOMAIN_NAME: "Default"
  OS_PROJECT_NAME: "{{ PROJECT_NAME }} "
  OS_TENANT_NAME: "{{ PROJECT_NAME }}"
  OS_USERNAME: "admin"
  OS_PASSWORD: "FKJ5zNaThJDs5IPU34Fp8eKgrGN7YV31nJZZYWZu"
  OS_AUTH_URL: "http://10.100.145.54:5000"
  OS_INTERFACE: "internal"
  OS_ENDPOINT_TYPE: "internalURL"
  OS_IDENTITY_API_VERSION: "3"
  OS_REGION_NAME: "RegionOne"
  OS_AUTH_PLUGIN: "password"
  OS_PROJECT_ID: "{{ PROJECT_ID.projects[0].id }} "
  OS_DOMAIN_ID: "default"
  OS_INSECURE: "true"

vmware_path: "/{{ datacenter }}/{{ folder }}/{{ vm }}"

docker_image: "mariolan/migratekit:latest"
docker_command: "migrate"
docker_privileged: true
docker_network: "host"
docker_volumes:
  - "/dev:/dev"
  - "/usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro"
docker_env_file: "<(env | grep OS_)"

network_mappings:
  - mac: "{{ mac_address1 }}"
    network_id: "{{ network_id1 }}"
    subnet_id: "{{ subnet_id1 }}"
    ip: "{{ vm_ip1 }}"
  - mac: "{{ mac_address2 }}"
    network_id: "{{ network_id2 }}"
    subnet_id: "{{ subnet_id2 }}"
    ip: "{{ vm_ip2 }}"