---
- name: Cutover the VM to OpenStack
  become: yes
  become_user: root
  ansible.builtin.shell: |
    docker run --rm \
    --privileged \
    --network host \
    -v /dev:/dev:ro \
    -v /usr/lib64/vmware-vix-disklib/:/usr/lib64/vmware-vix-disklib:ro \
    -e OS_PROJECT_DOMAIN_NAME="{{ openstack_project_domain_name }}" \
    -e OS_USER_DOMAIN_NAME="{{ openstack_user_domain_name }}" \
    -e OS_PROJECT_NAME="{{ openstack_project_name }}" \
    -e OS_TENANT_NAME="{{ openstack_tenant_name }}" \
    -e OS_USERNAME="{{ openstack_username }}" \
    -e OS_PASSWORD="{{ openstack_password }}" \
    -e OS_AUTH_URL="{{ openstack_auth_url }}" \
    -e OS_INTERFACE="{{ openstack_interface }}" \
    -e OS_ENDPOINT_TYPE="{{ openstack_endpoint_type }}" \
    -e OS_IDENTITY_API_VERSION="{{ openstack_identity_api_version }}" \
    -e OS_REGION_NAME="{{ openstack_region_name }}" \
    -e OS_AUTH_PLUGIN="{{ openstack_auth_plugin }}" \
    -e OS_PROJECT_ID="{{ openstack_project_id }}" \
    -e OS_DOMAIN_ID="{{ openstack_domain_id }}" \
    -e OS_INSECURE="{{ openstack_insecure }}" \
    "{{ docker_image }}" cutover \
    --availability-zone "{{ availability_zone }}" \
    --vmware-endpoint "{{ vmware_endpoint }}" \
    --vmware-username "{{ vmware_username }}" \
    --vmware-password "{{ vmware_password }}" \
    --vmware-path "{{ vmware_path }}" \
    --flavor "{{ flavor }}" \
    --network-mapping mac="{{ network-id }}",subnet-id="{{ subnet-id }}",ip="{{ vm_ip }}"
  register: docker_output

- name: Display the output of the command
  debug:
    msg: "{{ docker_output.stdout }}"

