---
- name: Migration of VM from VMware to OpenStack
  become: yes
  become_user: root
  docker_container:
    name: migratekit_container
    image: "{{ docker_image }}"
    command: >
      cutover
      --availability-zone {{ availability_zone }}
      --vmware-endpoint {{ vmware_endpoint }}
      --vmware-username {{ vmware_username }}
      --vmware-password {{ vmware_password }}
      --vmware-path "{{ vmware_path }}"
      --flavor "{{ flavor }}"
      {% for net in network_mappings %}
      --network-mapping mac={{ net.mac }},network-id={{ net.network_id }},subnet-id={{ net.subnet_id }},ip={{ net.ip }}
      {% endfor %}
#      --network-mapping mac={{ mac_address }},network-id={{ network_id }},subnet-id={{ subnet_id }},ip={{ vm_ip }}
    network_mode: "{{ docker_network }}"
    privileged: "{{ docker_privileged }}"
    volumes: "{{ docker_volumes }}"
    env: "{{ openstack_env }}"
    # env_file: "{{ docker_env_file }}"
    detach: false
    auto_remove: true
  register: migration_output

- name: Display Docker container output
  debug:
    var: migration_output.container.Output

