---
- name: Execute Docker run command with Ansible
  hosts: all
  gather_facts: false
  tasks:
    - name: Migrate
      ansible.builtin.import_role:
        name: migrate
      tags: migrate
      when: "action == 'migrate'"

    - name: Cutover
      ansible.builtin.import_role:
        name: cutover
      tags: cutover
      when: "action == 'cutover'"
