---
- name: Ottieni ID del project
  openstack.cloud.project_info:
    auth:
      auth_url: "{{ openstack_env.OS_AUTH_URL }}"
      username: "{{ openstack_env.OS_USERNAME }}"
      password: "{{ openstack_env.OS_PASSWORD }}"
      project_name: "{{ openstack_env.OS_PROJECT_NAME }}"
      user_domain_name: "{{ openstack_env.OS_USER_DOMAIN_NAME }}"
      project_domain_name: "{{ openstack_env.OS_PROJECT_DOMAIN_NAME }}"
    region_name: "{{ openstack_env.OS_REGION_NAME }}"
    interface: internal
    validate_certs: false
    name: "{{ PROJECT_NAME }}"
  register: PROJECT_ID

- name: Set OS_PROJECT_ID
  set_fact:
    openstack_env: "{{ openstack_env | combine({'OS_PROJECT_ID': PROJECT_ID.projects[0].id}) }}"

- name: Debug openstack_env
  debug:
    var: openstack_env

- name: Migration of VM from VMware to OpenStack
  become: yes
  become_user: root
  docker_container:
    name: migratekit_container
    image: "{{ docker_image }}"
    command: >
      migrate
      --availability-zone {{ availability_zone }}
      --vmware-endpoint {{ vmware_endpoint }}
      --vmware-username {{ vmware_username }}
      --vmware-password {{ vmware_password }}
      --vmware-path "{{ vmware_path }}"
    network_mode: "{{ docker_network }}"
    privileged: "{{ docker_privileged }}"
    volumes: "{{ docker_volumes }}"
    env: "{{ openstack_env }}"
    # env_file: "{{ docker_env_file }}"
    detach: false
    auto_remove: true
  register: migration_output

- name: Display Docker container output
  debug:
    var: migration_output.container.Output


