---
- name: Migration of VM from VMware to OpenStack
  become: yes
  become_user: root
  docker_container:
    name: migratekit_container
    image: "{{ docker_image }}"
    command: >
      migrate
      --availability-zone {{ availability_zone }}
      --vmware-endpoint {{ vmware_endpoint }}
      --vmware-username {{ vmware_username }}
      --vmware-password {{ vmware_password }}
      --vmware-path "{{ vmware_path }}"
    network_mode: "{{ docker_network }}"
    privileged: "{{ docker_privileged }}"
    volumes: "{{ docker_volumes }}"
    env: "{{ openstack_env }}"
    # env_file: "{{ docker_env_file }}"
    detach: false
    auto_remove: true
    output_logs: true
  register: container_output

- name: Display container output
  debug:
    msg: "{{ container_output.stdout }}"

