---
- name: Verifica raggiungibilità degli host
  hosts: all
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - name: Esegui ping sugli host
      ansible.builtin.ping:
    - name: Filtra le variabili d'ambiente che iniziano con OS_ e salva in un file temporaneo
      shell: |
        whoami
